name: bookswap_app
description: A marketplace where students can list textbooks and initiate swap offers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  intl: ^0.20.2
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/