name: bookswap_app
description: A marketplace where students can list textbooks and initiate swap offers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  intl: ^0.20.2
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/